djangular/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('layerfive.urls', namespace='api')),
    path('admin/', admin.site.urls),
]

layerfive/urls.py
from django.views.generic import TemplateView
from django.urls import path
from .views import CreateUserDescription

app_name = 'layerfive'


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('show', TemplateView.as_view(template_name='show.html'), name='show'),
    path('create', CreateUserDescription.as_view()),
]

layerfive/models.py
from django.db import models


class UserDescription(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    email = models.EmailField(max_length=70)
    mobile = models.IntegerField()
    address1 = models.TextField(null=True, blank=True)
    address2 = models.TextField(null=True, blank=True)
    city = models.CharField(max_length=15)
    zipcode = models.IntegerField()
    state = models.CharField(max_length=15)

    class Meta:
        verbose_name_plural = 'User Description'

    def __str__(self):
        return self.firstname + self.lastname

layerfive/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import UserDescription
from .serializers import UserDescriptionSerializer


class CreateUserDescription(APIView):

    def get(self, request, format=None):
        users = UserDescription.objects.all()
        serializer = UserDescriptionSerializer(users, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request, format=None):
        print(request.data)
        serializer = UserDescriptionSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
</head>
<body ng-app="LayerFive">

<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    const app = angular.module("LayerFive", []);

</script>

<div class="container">
    {% block content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Layerfive User DetailForm
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-12" ng-controller="UserDetails">
            <form>
                {% csrf_token %}
                <div class="form-group">
                    <label for="firstname">Enter Firstname</label>
                    <input type="text" class="form-control" ng-model="firstname" required>
                </div>
                <div class="form-group">
                    <label for="lastname">Enter Lastname</label>
                    <input type="text" class="form-control" ng-model="lastname" required>
                </div>
                <div class="form-group">
                    <label for="email">Enter Email</label>
                    <input type="email" class="form-control" ng-model="email" required>
                </div>
                <div class="form-group">
                    <label for="mobile">Enter Mobile Number</label>
                    <input type="tel" class="form-control" ng-model="mobile" required>
                </div>
                <div class="form-group">
                    <label for="address1">Address 1</label>
                    <input type="text" class="form-control" ng-model="address1">
                </div>
                <div class="form-group">
                    <label for="address2">Address 2</label>
                    <input type="text" class="form-control" ng-model="address2">
                </div>
                <div class="form-group">
                    <label for="city">Enter City</label>
                    <input type="text" class="form-control" ng-model="city" required>
                </div>
                <div class="form-group">
                    <label for="zipcode">Enter Pincode</label>
                    <input type="tel" class="form-control" ng-model="zipcode" required>
                </div>
                <div class="form-group">
                    <label for="state">Enter State</label>
                    <input type="text" class="form-control" ng-model="state" required>
                </div>
                <button class="btn btn-primary" ng-click="create()">Submit</button>
                <a href="{% url 'api:show' %}" class="btn btn-primary">Show Details</a>
            </form>
        </div>
    </div>

    <script>

        app.controller("UserDetails", ($scope, $http) => {
            $scope.create = () => {
                const url = 'http://127.0.0.1:8000/create';
                const userobj = {
                    "firstname": $scope.firstname,
                    "lastname": $scope.lastname,
                    "email": $scope.email,
                    "mobile": $scope.mobile,
                    "address1": $scope.address1,
                    "address2": $scope.address2,
                    "city": $scope.city,
                    "zipcode": $scope.zipcode,
                    "state": $scope.state
                };

                $http({
                    method: 'POST',
                    url: url,
                    data: JSON.stringify(userobj),
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrftoken
                    }
                })
                    .then((response) => window.location.href = '/show')
                    .catch((err) => alert("Something went wrong"));
            }
        });

    </script>

{% endblock %}

templates/show.html
{% extends 'base.html' %}

{% block title %}
    Layerfive User Details
{% endblock %}


{% block content %}

    <div class="row" ng-controller="Details" style="margin-left: auto; margin-right: auto; width: 90%;">
        <div class="col-md-12">
            <button ng-click="show()">Show Records</button>
            <input type="hidden" ng-model="errorstate">
            <div class="alert alert-danger" ng-show="errorstate">
                {% verbatim %} {{ userdetail }} {% endverbatim %}
            </div>
        </div>
        <div class="card" style="width: 18rem; margin-right: 5px; " ng-repeat="data in records">
            <div class="card-body">
                <h3 class="card-title">{% verbatim %} {{ data.firstname }} {{ data.lastname }} {% endverbatim %}</h3>
                <h4>Email</h4>
                <p class="card-text">{% verbatim %} {{ data.email }} {% endverbatim %}</p>
                <h4>Mobile</h4>
                <p class="card-text">{% verbatim %} {{ data.mobile }} {% endverbatim %}</p>
                <h5>Address</h5>
                <p class="card-text">{% verbatim %} {{ data.address1 }} {% endverbatim %}</p>
                <p class="card-text">{% verbatim %} {{ data.address2 }} {% endverbatim %}</p>
                <p class="card-text">{% verbatim %} {{ data.address2 }} {% endverbatim %}</p>
                <p class="card-text">{% verbatim %} {{ data.city }} {% endverbatim %}</p>
                <p class="card-text">{% verbatim %} {{ data.zipcode }} {% endverbatim %}</p>
                <p class="card-text">{% verbatim %} {{ data.state }} {% endverbatim %}</p>

            </div>
        </div>
    </div>

    <script>
        app.controller("Details", ($scope, $http) => {
            const url = "http://127.0.0.1:8000/create";

            $scope.show = () => {
                $http.get(url)
                    .then((response) => $scope.records = response.data)
                    .catch((err) => {
                        $scope.errorstate = false;
                        $scope.userdetail = "No user details posted yet";
                    });
            }
        });
    </script>

{% endblock %}